# Autogenerated wrapper script for GANAK_jll for powerpc64le-linux-gnu-cxx11
export ganak, libganak

using GMP_jll
using MPFR_jll
using FLINT_jll
using Zlib_jll
using cereal_jll
using armadillo_jll
using ensmallen_jll
using mlpack_jll
JLLWrappers.@generate_wrapper_header("GANAK")
JLLWrappers.@declare_library_product(libganak, "libganak.so.1.1")
JLLWrappers.@declare_executable_product(ganak)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, MPFR_jll, FLINT_jll, Zlib_jll, cereal_jll, armadillo_jll, ensmallen_jll, mlpack_jll)
    JLLWrappers.@init_library_product(
        libganak,
        "lib/libganak.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ganak,
        "bin/ganak",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
